database:
  url: jdbc:mysql://localhost:3306/note?useUnicode=true&characterEncoding=utf-8
  username: root
  password: pass
spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: true
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

feign:
  notificationCenter:
    name: notification
    url: http://localhost:8081